<?php
  echo "<!DOCTYPE HTML>\n";
  echo "<html lang=\"en\">\n";
  echo "    <head>\n";
  echo "        <meta charset=\"utf-8\"/>\n";
  echo "        <link rel=\"stylesheet\" type=\"text/css\" href=\"style7.css\">\n";
  echo "        <link href=\"https://fonts.googleapis.com/css?family=Questrial|Varela+Round\" rel=\"stylesheet\">\n";
  echo "        <link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.css\">\n";
  echo "        <title>My Website</title>\n";
  echo "    </head>\n";
  echo "    <body>\n";
  echo "        <div class=\"container\">\n";
  echo "            <header class=\"row\">\n";
  echo "                <div class=\"header\">\n";
  echo "                    <H1>MENUISERIE EMERIC LEBON</H1>\n";
  echo "                </div>\n";
  echo "            </header>\n";
  echo "            <div class=\"row\">\n";
  echo "                <nav class=\"navbar navbar-inverse\">\n";
  echo "                    <div class=\"container-fluid\">\n";
  echo "                        <ul class=\"nav navbar-nav\">\n";
  echo "                            <li role=\"presentation\" class=\"inactive\"><a href=\"accueil.html\"><span class=\"glyphicon glyphicon-home\" style=\"color:#BBB;\"></span>  Accueil</a></li>\n";
  echo "                            <li role=\"presentation\" class=\"active\"><a href=\"contact.php\"><span class=\"glyphicon glyphicon-phone\" style=\"color:#BBB;\"></span>  Contact</a></li>\n";
  echo "                        </ul>\n";
  echo "                    </div>\n";
  echo "                </nav>\n";
  echo "            </div>\n";
  echo "\n";
  echo "            <div class=\"row\">\n";
  echo "                <div id=\"text\">\n";
  echo "                    <p>\n";
  echo "                    Bonjour,\n";
  echo "                    Je suis Emeric Lebon.\n";
  echo "                    Si vous voulez me contacter, remplissez le formulaire ci-desous.\n";
  echo "                    </p>\n";
  echo "                </div>\n";
  echo "            </div>\n";
  echo "            <div class=\"row\">\n";
  echo "                <form class=\"col-lg-5\">\n";
  echo "                    <H2><span class=\"label label-primary\"><span class=\"glyphicon glyphicon-envelope\" style=\"color:#FFF;\"></span> Contact :</span></H2>\n";
  echo "                    <legend>Genre : </legend>\n";
  echo "                      <div class=\"radio\">\n";
  echo "                          <label for=\"male\" class=\"radio\">\n";
  echo "                              <input type=\"radio\" name=\"gender\" value=\"male\" id=\"male\">\n";
  echo "                                  Homme\n";
  echo "                          </label>\n";
  echo "                      </div>\n";
  echo "                        <div class=\"radio\">\n";
  echo "                            <label for=\"female\" class=\"radio\">\n";
  echo "                                <input type=\"radio\" name=\"gender\" value=\"female\" id=\"female\">\n";
  echo "                                    Femme\n";
  echo "                            </label>\n";
  echo "                        </div>\n";
  echo "                        <div class=\"radio\">\n";
  echo "                            <label for=\"other\" class=\"radio\">\n";
  echo "                                <input type=\"radio\" name=\"gender\" value=\"other\" id=\"other\">\n";
  echo "                                    Autre\n";
  echo "                            </label>\n";
  echo "                        </div>\n";
  echo "                        <div class=\"form-group\">\n";
  echo "                            <label for=\"texte\">Prénom : </label>\n";
  echo "                            <input type=\"text\" class=\"form-control\" required name=\"prenom\" placeholder=\"François\"/>\n";
  echo "                            <label for=\"texte\">Nom : </label>\n";
  echo "                            <input type=\"text\" class=\"form-control\" required name=\"nom\" placeholder=\"Dupond\"/>\n";
  echo "                            <label for=\"texte\">Email : </label>\n";
  echo "                            <input type=\"text\" class=\"form-control\" required name=\"email\" placeholder=\"francoisdupond@email.com\"/>\n";
  echo "                            <label for=\"texte\">Adresse : </label>\n";
  echo "                            <input type=\"text\" class=\"form-control\" required name=\"adresse\" placeholder=\"3 rue Victor Hugo\"/>\n";
  echo "                            <label for=\"texte\">Code postal : </label>\n";
  echo "                            <input type=\"text\" class=\"form-control\" required name=\"code_postal\" placeholder=\"31000\"/>\n";
  echo "                            <label for=\"texte\">Ville : </label>\n";
  echo "                            <input type=\"text\" class=\"form-control\" required name=\"ville\" placeholder=\"Toulouse\"/>\n";
  echo "                            <label for=\"texte\">Téléphone : </label>\n";
  echo "                            <input type=\"text\" class=\"form-control\" required name=\"telephone\" placeholder=\"06 38 40 50 29\"/>\n";
  echo "                        </div>\n";
  echo "                        <div class=\"form-group\">\n";
  echo "                            <label for=\"textarea\">Message : </label>\n";
  echo "                            <textarea id=\"textarea\" name=\"message\" rows=\"8\" type=\"textarea\" class=\"form-control\" placeholder=\"\">
?>
